### ISSUE TITLE
Feature Request: Hide Status Bar item when not typing

### ISSUE THREAD

**Issue by chrisgrieser** [Supercip971/obsidian-typing-speed#3]
I like the idea of darkening the item when not typing. How about completely hiding the item when not typing? constantly having the `0` shown there seems a bit pointless, when you are jsut browsing things in your vault

**Comment by Supercip971** [comment]
Wouldn't be-it weird if you had a blank spot in the status bar ? or it should be disappearing, and every item in the status bar will be shifted every-time you stop writing ? :thinking: (I'll add it anyway as an option).

**Comment by chrisgrieser** [comment]
well, for me the plugin is at the left-most, so it doesn't really shift things.

The blank spot could be easily fixed with adding this to the `styles.css`:


```css
.status-bar-item.plugin-typing-speed:empty {
  display: none;
}
```

**Comment by Supercip971** [comment]
Ow that mean that I should add an option to force the counter to be at the left-most of the status bar (if it’s possible) because on my side it is surrounded by other plugins.

**Comment by Supercip971** [comment]
After nearly two years I finally closed this issue, thank you a lot for your suggestion and patience !
