### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Opisek** [Supercip971/obsidian-typing-speed#8]
My obsidian started having extreme lagging issues since the last obsidian update, both on my laptop and stationary computer.

After disabling all my plugins and trying to enable them invididually, I found the lag to only appear once I turn on the typing speed plugin.

I don't know to what degree you are able to fix this, but I would love if you could investigate why that happens. Until then, I must sadly turn this plugin off.

Simple comparison:
Try holding the up/down arrow in a ~500 lines long file with and without this plugin being enabled.

**Comment by Supercip971** [comment]
Hello ! 

I don't know how to reproduce this bug. I tried multiple time on the latest version of obsidian and even with a file with 1000+ lines, I could not see any lag. I'll try to look into this in the next few days.

Sorry for the inconvenience.  

What is the obsidian version you are currently using ?

**Comment by Opisek** [comment]
Thanks a lot for your response.

Version 1.7.4

I just noticed the lag doesn't appear for me if I don't have Vim mode enabled.

Apologies for taking your time with this issue, since now I can't for sure say that this plugin is the root cause of the issue.

I suspect the plugin may behave differently when an arrow key is held down vs when hjkl movement keys in vim are held down. It would be great if you can check that on your system as well.

If you still can't reproduce the problem, then I'll try to look for the cause somewhere else.

**Comment by Supercip971** [comment]
Ok, I still can't reproduce the problem on my side. But I still tried to improve the performance in the current release (v1.3.0). 
And don't apologies ! Thank you a lot for helping me tackle this issue ! You are not wasting my time !

**Comment by Opisek** [comment]
Thanks a lot for your effort!

**Comment by Opisek** [comment]
Thanks a lot for your effort!

**Comment by Opisek** [comment]
I have now narrowed my issues down to my obsidian theme "Minimal". Once again thanks for all your effort. I'm sure every little performance improvement here and there help the bigger picture, as well.
